name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.17.0]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run type check
      run: npm run type-check
    
    - name: Build extension
      run: npm run build
    
    - name: Verify build output
      run: |
        # Check if dist directory exists
        if [ ! -d "dist" ]; then
          echo "❌ Build failed: dist directory not found"
          exit 1
        fi
        
        # Check if manifest.json exists
        if [ ! -f "dist/manifest.json" ]; then
          echo "❌ Build failed: manifest.json not found"
          exit 1
        fi
        
        # Verify manifest.json is valid JSON
        if ! node -e "JSON.parse(require('fs').readFileSync('dist/manifest.json', 'utf8'))"; then
          echo "❌ Build failed: manifest.json is not valid JSON"
          exit 1
        fi
        
        # Check if main files exist
        if [ ! -f "dist/src/options/index.html" ]; then
          echo "❌ Build failed: options index.html not found"
          exit 1
        fi
        
        # Check if service worker exists
        if [ ! -f "dist/service-worker-loader.js" ]; then
          echo "❌ Build failed: service-worker-loader.js not found"
          exit 1
        fi
        
        # Check if assets directory exists
        if [ ! -d "dist/assets" ]; then
          echo "❌ Build failed: assets directory not found"
          exit 1
        fi
        
        echo "✅ Build verification passed"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extension-build
        path: dist/
        retention-days: 7