name: Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in dry-run mode (no actual submission)'
        required: false
        type: boolean
        default: false

jobs:
  Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      version_changed: ${{ steps.check_version.outputs.version_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for version change
        id: check_version
        run: |
          if git diff --name-only HEAD~1..HEAD | grep -q '^package\.json$'; then
            VERSION_CHANGED=1
          else
            VERSION_CHANGED=0
          fi
          echo "version_changed=$VERSION_CHANGED" >> "$GITHUB_OUTPUT"
      - name: Get version
        if: ${{ steps.check_version.outputs.version_changed == '1' }}
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  Submit:
    needs: Version
    if: ${{ needs.Version.outputs.version_changed == '1' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Zip extensions
        run: npm run zip

      - id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT

      - name: Submit to stores
        run: |
          npm run wxt submit \
            --chrome-zip .output/${{steps.repository.outputs.name}}-${{ needs.Version.outputs.version }}-chrome.zip \
            ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dry-run == 'true' && '--dry-run' || '' }}
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.Version.outputs.version }}"
          name: "v${{ needs.Version.outputs.version }}"
          draft: false
          prerelease: false
          files: |
            .output/${{steps.repository.outputs.name}}-${{ needs.Version.outputs.version }}-chrome.zip
